export const ConnectionType = {
  METAMASK: 'METAMASK',
  WALLET_CONNECT: 'WALLET_CONNECT',
  NETWORK: 'NETWORK',
  OKX: 'OKX',
  TRONLINK: 'TRONLINK',
  APTOS_PETRA: 'APTOS_PETRA',
  RONIN: 'RONIN',
  COMPASS: 'COMPASS',
  PHANTOM: 'PHANTOM',
  SUI: 'SUI',
};

export const TYPE_OF_CHAIN = {
  EVM: 'ERC20',
  TRON: 'TRON_GRID_MAINNET',
  APTOS: 'APTOS_MAINNET',
  SEI: 'SEI_MAINNET',
  RONIN: 'RONIN',
  COMPASS: 'COMPASS',
  PHANTOM: 'PHANTOM',
  SUI: 'SUI',
};
